apiVersion: apps/v1
kind: Deployment

metadata:
  metadata:
  name: event-post-service
  namespace: notification-app

spec:

  replicas: 1

  selector:
    matchLabels:
      app: event-post-service

  template:

    metadata:
      labels:
        app: event-post-service

    spec:

      containers:

      - name: event-post-service

        image: eventposting:latest

        imagePullPolicy: Never

        env:

        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
