apiVersion: v1
kind: Secret

metadata:
  name: notification-secret
  namespace: notification-app

type: Opaque

stringData:
  SPRING_MAIL_USERNAME: bedcc19bd4f5e4
  SPRING_MAIL_PASSWORD: f82f3cb6cd0678
