apiVersion: v1
kind: ConfigMap

metadata:
  name: notification-config
  namespace: notification-app

data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  SPRING_KAFKA_CONSUMER_GROUP_ID: "email-notification-group"
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: "earliest"

  APP_KAFKA_TOPIC: "notification-events"
  APP_KAFKA_RETRY_MAX_ATTEMPTS: "3"
  APP_KAFKA_RETRY_BACKOFF_MS: "2000"

  SPRING_MAIL_HOST: "sandbox.smtp.mailtrap.io"
  SPRING_MAIL_PORT: "2525"

  APP_MAIL_FROM: "noreply@notification-service.local"
  APP_MAIL_SUBJECT_PREFIX: "[Notification Process]"

  LOGGING_LEVEL_COM_NOTIFICATIONAPP: "DEBUG"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA: "INFO"
