apiVersion: apps/v1
kind: Deployment

metadata:
  name: notification-service
  namespace: notification-app

spec:

  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:

    metadata:
      labels:
        app: notification-service

    spec:

      containers:

      - name: notification-service

        image: notificationgenerator:latest

        imagePullPolicy: Never

        envFrom:
        - configMapRef:
            name: notification-config

        - secretRef:
            name: notification-secret
