# =====================================
# Kafka
# =====================================

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=email-notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.kafka.topic=notification-events
app.kafka.retry.max-attempts=3
app.kafka.retry.backoff-ms=2000


# =====================================
# Mailtrap SMTP
# =====================================

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525

spring.mail.username=bedcc19bd4f5e4
spring.mail.password=f82f3cb6cd0678

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =====================================
# Application Mail Settings
# =====================================

app.mail.from=noreply@notification-service.local
app.mail.subject-prefix=[Notification Process]

# =====================================
# Logging
# =====================================

logging.level.com.notificationapp=DEBUG
logging.level.org.springframework.kafka=INFO