
# Select rate limiter config source: 'yaml' or 'properties'
rate-limiter.config-source=yaml
spring.config.import=optional:classpath:Config/fixed-window.yml

#Kafka Configuration
KAFKA_BOOTSTRAP_SERVERS=localhost:9092
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
logging.level.org.jline=DEBUG
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Redis Connection Details
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=your_password_here  # Uncomment if auth is required

# Connection Pool Settings (Requires commons-pool2 dependency)
spring.data.redis.lettuce.pool.max-active=16
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.timeout=2000ms

# PostgreSQL Settings
spring.datasource.url=jdbc:postgresql://localhost:5433/ratelimiter_db
spring.datasource.username=postgres
spring.datasource.password=postgrespassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable or disable JWT authentication across the application
authentication.required=false
# Password encoder configuration bean
jwt.secret=1PGgvQSz+mzNTWQRPDkwC4nF89MCTpcGbg8/wqwKNeU=


# Root logging level (keeps noise down for 3rd party libraries)
logging.level.root=INFO

# Your application package (replace with your actual package name)
logging.level.com.notificationapp=DEBUG

# Log Spring Data Redis operations
logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.data.redis.core.RedisConnectionUtils=DEBUG

# Log underlying Lettuce driver commands and payload execution
logging.level.io.lettuce.core=DEBUG

# Enable full Spring Security filter chain debugging
logging.level.org.springframework.security=DEBUG

# Enable detailed web request logging
logging.level.org.springframework.web=DEBUG

management.endpoints.web.exposure.include=configprops,health
management.endpoint.configprops.show-values=ALWAYS

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration